CC=g++
CFLAGS=-I../include

base: string punto vector color escena configuracion raytracer

string:
	$(CC) $(CFLAGS) -c String.cpp

punto:
	$(CC) $(CFLAGS) -c Punto.cpp

vector:
	$(CC) $(CFLAGS) -c Vector.cpp

color:
	$(CC) $(CFLAGS) -c Color.cpp

configuracion:
	$(CC) $(CFLAGS) -c Configuracion.cpp

escena:
	$(CC) $(CFLAGS) -c Escena.cpp

raytracer:
	$(CC) $(CFLAGS) -c Raytracer.cpp

clean:
	rm -rf *.o


